version: 0.0
os: linux
files:
  - source: /
    destination: ~/
    overwrite: true
  - object: /
    pattern: '**'
    owner: dim
    group: dim
hooks:
  Install:
    - location: scripts/start_server.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
