version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes
    runas: ec-user

permissions:
  - object: /
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user

  BeforeInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: ec2-user
