openapi: 3.0.3
info:
  title: rade API
  description: |-
    보스 몬스터를 잡은 결과를 Ranking으로 보여주는 서비스입니다
servers:
  - url: http://localhost:3000
tags:
  - name: user
    description: 유저에 대한 CR API
    externalDocs:
      description: 유저를 생성하고 조회합니다
      url: http://localhost:3000/user

  - name: bossRaid
    description: boss Raid 대한 API 입니다
    externalDocs:
      description: boss Raid에 관한 데이터를 제공합니다
      url: http://localhost:3000/bossRaid
paths:
  /user:
    post:
      tags:
        - user
      summary: 유저 등록
      description: 새로운 유저를 등록합니다
      operationId: createUser
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    example: 1
        '500':
          description: Internal Server Error
  /bossRaid:
    get:
      tags:
        - bossRaid
      summary: 보스 raid 정보를 가져옵니다
      description: 보스 레이드 시도가 가능한지 알 수 있습니다
      operationId: getBossState
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
              examples:
                result1:
                  value:
                    canEnter: true
                result2:
                  value:
                    canEnter: false
                    userId: 1
        '500':
          description: Internal Server Error
